---
- name: install postgreSQL
  become: true
  pacman:
    name: postgresql
    state: present

- name: create data directory
  become: true
  file:
    path: /var/lib/postgres/data
    state: directory
    owner: postgres
    group: postgres

- name: initialize database
  become: true
  shell: initdb -E UTF8 -D '/var/lib/postgres/data'
  become_user: postgres
  notify:
    - start_postgres

- name: copy database configuration files
  become: true
  template:
    src: pg_hba.conf
    dest: /var/lib/postgres/data/
